[project]
name = "mdsw-webapp"
version = "0.1.2"
description = "Web app for MDSW"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.52.2",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
